---
pagetitle: GCAM-China

---

<div class="header_logo">
Add logos if desired
</div>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

# Community Guidelines

<div class="container">
  <h2>Guidelines</h2>
  <p>
   GCAM-China 模型社区管理章程


GCAM-China 模型社区（以下简称“社区”）旨在构建一个高效、包容、开放的学术交流平台，以促进经验交流、学术进步和技术创新。本章程包含社区的目标、原则和组织架构。通过自发组织开发和维护 GCAM-China，旨在使其成为国内外同行学术研究和政策制定的重要工具。


第一部分：愿景与宗旨
●	愿景：建立GCAM-China用户群体自发组织的平台，促进科学交流、学术进步和技术创新，服务相关领域的发展。
●	宗旨：通过自发组织开发和维护，将GCAM-China开发成为研究和政策制定的重要辅助工具，促进科学交流和学术进步。

第二部分：核心原则
●	包容性：鼓励各学科背景的研究人员参与，促进不同观点的交流，以实现更广泛的思想碰撞和创新。
●	开放透明：坚持开放透明的原则，重视代码的完整性和研究的可重复性。
●	科学严谨性：通过同行评审和代码审查维护模型质量，确保研究结果的可靠性和科学性。

第三部分：目标与策略
●	服务社区：协调社区成员的研究兴趣和资源，互帮互助，共同促进成员的研究项目和职业发展，特别是青年学者的模型基础积累。
●	学术合作：与国内外综合评估模型团队和相关领域专家合作，保持与GCAM 核心开发团队的密切联系，积极参与不同尺度的多模型比较研究，促进学术交流和模型长远发展。
●	政策支持：模型开发立足中国政策需求，为决策者提供实际科学支持，推动科学研究和政策制定的结合。

第四部分：组织结构与角色
●	开源平台：使用GitHub作为开源平台。
●	顾问委员会：由本领域知名专家和资深模型开发人员组成，提供科学指导，制定长期发展计划。
●	模型开发委员会：负责日常管理核心代码，审核新功能，组织各种形式的培训，以确保模型的稳定运行和科学严谨。
●	模型学习应用小组：由模型初学者和日常使用者自发组织，通过多种形式经验分享，由模型开发成员提供技术支持。

第五部分：交流与合作
●	社区讨论：利用 GitHub 、微信等平台进行技术交流和协作，使成员及时分享代码、讨论问题和提出建议。
●	季度通讯：发布季度通讯，分享最新进展、研究成果和即将举行的活动，保持成员的知悉和参与。
●	培训活动：定期举办线上或线下培训，提升社区成员的开发技能和模型知识。
●	年度研讨会：社区举办年度研讨会，促进线下交流，讨论模型的最新发展和未来方向，加强合作和创新。

第六部分：合作与参与方式
●	鼓励任何对GCAM-China 感兴趣的个人/课题组/单位加入社区，与社区成员进行各种形式的合作。
●	使用社区模型产生的各类成果，应本着学术诚信的原则，对现有贡献（平台维护人员和相关核心功能的开发者等）给予应有的尊重。
●	针对新功能模块的开发计划，建议与模型开发委员会成员积极沟通，以便社区内协调资源，获得帮助，避免重复劳动。



 

GCAM-China 模型社区成员名单

顾问委员会（姓氏首字母排列）：
蔡闻佳
清华大学

Ryna Cui	University of Maryland
戴瀚程
北京大学

Jae Edmonds	Pacific Northwest National Laboratory
Allen Fawcett	Pacific Northwest National Laboratory
Kuishuang Feng	University of Maryland
Nate Hultman	University of Maryland
Gokul Iyer	Pacific Northwest National Laboratory
Haewon McJecon	Korea Advanced Institute of Science and Technology
姜克隽
国家发展和改革委员会能源研究所

李佳硕
山东大学

刘宇
北京大学

鲁玺
清华大学

Pralit Patel	Pacific Northwest National Laboratory
滕飞
清华大学

同丹
清华大学

王灿
清华大学

王书肖
清华大学

Sha Yu	University of Maryland
汪鹏
中国科学院城市环境研究所

张强
清华大学

段宏波
中国科学院大学


模型开发委员会：

偶阳
北京大学

刘洋
清华大学

Andy Miller	University of Maryland
Jay Fuhrman	Pacific Northwest National Laboratory


模型学习应用小组：
各校正在使用GCAM的博士/博后（目前约有30人）
 
GCAM-China Community Guidelines

The GCAM-China Community (hereinafter referred to as “the Community”) is dedicated to fostering an inclusive environment that facilitates the exchange of knowledge, advances in scientific research, and the innovation of modeling techniques. These guidelines outline the Community’s goals, ethical principles, and organizational framework. By collectively orchestrating the development and maintaince of GCAM-China, we strive to transform it into a pivotal resource for academic research and policy formulation, accessible to both national and international researchers and stakeholders.

Section I: Vision and Mission

Vision: To cultivate a self-sustaining ecosystem for GCAM-China users, enabling the dissemination of knowledge, scientific progress, and technological breakthroughs.

Mission: To leverage communal efforts in the evolution and stewardship of GCAM-China, thereby establishing it as a key instrument for scholarly and policy-oriented investigations, and to foster scientific advancement.

Section II: Foundational Principles

Inclusivity: We invite contributions from scholars across all disciplines and all career stages to enrich discussions, spark innovative ideas, and foster diverse perspectives.

Transparency: We commit to a culture of openness and clarity, prioritizing code integrity and the replicability of research findings.

Scientific Integrity: We uphold the quality of our model through rigorous peer reviews, promoting the accuracy and scholarly merit of our research outputs.

Section III: Goals and Strategies

Community Support: We aim to synchronize the research interests and resources of community members, fostering mutual assistance and collectively enhancing the research endeavors and professional growth of our community, with a particular focus on supporting the career development of junior scholars.

Academic Collaboration: We engage in partnerships with both China-based and international modeling teams and specialists, maintain close coordination with the GCAM core developers, actively participate in multi-model comparative analyses, and encourage academic exchanges and the sustained evolution of our model.

Policy oriented: Our model development is closely aligned with the needs of decision-supporting for Chinese policies, offering tangible scientific backing to decision-makers and bridging the gap between scientific exploration and policy formulation.

Section IV: Organizational Framework and Roles

Open-source Collaboration: We utilize GitHub as our primary platform for open-source collaboration.

Advisory Committee: This committee consists of esteemed experts and senior model developers who provide scientific oversight and strategic planning.

Model Development Committee: Tasked with the routine governance of core code, evaluation of new functionalities, and the facilitation of diverse training initiatives to ensure the model’s stable functionality and scientific accuracy.

User Group: Formed voluntarily by junior researchers that are regular users of the model, this group fosters knowledge sharing in flexible formats, supported by the model development team.

Section V: Communication and Collaboration

Community Engagement: We employ open-access platforms such as GitHub and WeChat  for technical discussions and collaborations, enabling members to conveniently share codes, discuss topics, and share collaborative opportunities.

Quarterly Newsletter: A newsletter is circulated every quarter to highlight recent advancements, research outcomes, and forthcoming activities, ensuring members stay informed and engaged.

Training Opportunities: We seek to organize various training sessions to enhance modeling and research skills of community members.

Annual Workshop: A yearly workshop is expected to hold to facilitate direct interactions, share the latest model updates, discuss future directions, and bolster collaborative opportunities.

Section VI: Engagement and Collaboration Opportunities

We welcome individuals, groups, and organizations interested in GCAM-China to join our community and engage with fellow members in a variety of collaborative efforts.

Contributions utilizing the community-developed model must adhere to academic integrity principles, duly acknowledging prior contributions (e.g., platform maintainers, developers of key functionalities).

For propositions concerning the development of new functional modules, it is advisable to proactively liaise with the Model Development Committee to coordinate community resources, leverage assistance, and prevent redundant efforts.
 
GCAM-China community member list

Advisory Committee (listed alphabetically based on last names)

Wenjing Cai	Tsinghua University
Ryna Cui	University of Maryland
Hancheng Dai	Peking University
Jae Edmonds	Pacific Northwest National Laboratory
Allen Fawcett	Pacific Northwest National Laboratory
Kuishuang Feng	University of Maryland
Nate Hultman	University of Maryland
Gokul Iyer	Pacific Northwest National Laboratory
Haewon McJecon	Korea Advanced Institute of Science and Technology
Kejun Jiang	National Development and Reform Commission
Jiashuo Li	Shandong University
Yu Liu	Peking University
Xi Lu	Tsinghua University
Pralit Patel	Pacific Northwest National Laboratory
Fei Teng	Tsinghua University
Dan Tong	Tsinghua University
Can Wang	Tsinghua University
Shuxiao Wang	Tsinghua University
Sha Yu	University of Maryland
Peng Wang	Chinese Academy of Science
Qiang Zhang	Tsinghua University
Hongbo Duan	University of Chinese Academy of Science

Model Development Committee:

Yang Ou	Peking University
Yang Liu	Tsinghua University
Andy Miller	University of Maryland
Jay Fuhrman	Pacific Northwest National Laboratory


User Group：
Graduate students and postdocs currently using GCAM-China (about 30)

  </p>
</div>
